package com.example.myspeechy.domain

object AnimationConfig {
    const val BOTTOM_NAV_BAR_SHRINK_DURATION = 400
    const val MEDITATION_TIMESCROLLER_ANIMATION_DURATION = 600
    const val MEDITATION_TIMESCROLLER_TEXT_ANIMATION_DURATION = 200
    const val MEDITATION_BREATHING_ANIMATION_DURATION = 1000
}